# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyZONe8oIVBxyF0As4nbBE7zyrolbzGm
"""

import pandas as pd
import numpy as np
# Load the dataset
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')  # Encoding added if special characters exist
df.head()
# Check basic info
df.info()

# Check summary statistics
df.describe(include='all')
print(df.describe)

# Check null values
df.isnull().sum()
print(df.isnull().sum())

# Option 1: Drop rows with any nulls
df_cleaned = df.dropna()
print(df_cleaned)
# Recheck nulls
df_cleaned.isnull().sum()
print(df_cleaned.isnull().sum()
)

# Check for duplicates
print("Duplicates before:", df_cleaned.duplicated().sum())

# Drop duplicates
df_cleaned = df_cleaned.drop_duplicates()

print("Duplicates after:", df_cleaned.duplicated().sum())
# Example: Standardizing 'status' or 'country' columns (if they exist)
if 'status' in df_cleaned.columns:
    df_cleaned['status'] = df_cleaned['status'].str.lower().str.strip()
    print(df_cleaned['status'])
if 'country' in df_cleaned.columns:
    df_cleaned['country'] = df_cleaned['country'].str.title().str.strip()
    print(df_cleaned['country'])

# Try to parse likely date columns
date_columns = [col for col in df_cleaned.columns if 'date' in col.lower()]
for col in date_columns:
    df_cleaned[col] = pd.to_datetime(df_cleaned[col], errors='coerce')
print(df_cleaned[col])

# Rename columns to lowercase and use underscores
df_cleaned.columns = df_cleaned.columns.str.lower().str.replace(' ', '_')
print(df_cleaned.columns)

# Example: Convert 'quantityordered' to int if it exists
if 'quantityordered' in df_cleaned.columns:
    df_cleaned['quantityordered'] = df_cleaned['quantityordered'].astype(int)
    print(df_cleaned['quantityordered'])

df_cleaned.to_csv('cleaned_sales_data.csv', index=False)